// Offline visual/interaction fixture; never queries providers or reads app preferences.
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const now = Math.floor(Date.now()/1000), start=now-21600;
const symbols=['AAPL','MSFT','NVDA','GOOGL','AMZN','META'];
const prices=[228.4,431.2,138.6,183.4,219.5,578.8], quantities=[32,18,75,25,20,0];
const changes=[1.24,-.67,3.18,.84,-1.02,1.62];
const total=quantities.reduce((sum,n,i)=>sum+n*prices[i],0)+4200;
const quotes=symbols.map((symbol,i)=>({symbol,kind:'stock',currency:'USD',price:prices[i],regularPrice:prices[i]-.2,change:changes[i],regularChange:changes[i]-.08,quantity:quantities[i],value:quantities[i]?quantities[i]*prices[i]:null,weight:quantities[i]?quantities[i]*prices[i]/total*100:null,dayPL:quantities[i]?quantities[i]*prices[i]*changes[i]/100:null,unrealizedPL:quantities[i]?quantities[i]*prices[i]*.14:null,unrealizedPercent:14,averageCost:prices[i]/1.14,previousClose:prices[i]/(1+changes[i]/100),dayLow:prices[i]*.97,dayHigh:prices[i]*1.018,yearLow:prices[i]*.62,yearHigh:prices[i]*1.12,marketCap:2.9e12-i*2e11,volume:3.2e7+i*8e6,pe:24+i*3,session:'Regular session',receivedAt:now,sparkline:Array.from({length:90},(_,j)=>prices[i]*(.97+j*.00035+Math.sin(j/9+i)*.006)),earnings:i<3?{date:now+(i+2)*86400,session:i===0?'After close':'Before open',epsForecast:(1.5+i*.7).toFixed(2)}:undefined}));
const dayPL=quotes.reduce((s,q)=>s+(q.dayPL||0),0);
const curve=Array.from({length:120},(_,i)=>[start+i*180,total-420+i*3.2+Math.sin(i/13)*65]);
const snapshot={app:'Marketbar',portfolioID:'demo',portfolioName:'Long-term conviction',portfolios:[{id:'demo',name:'Long-term conviction'},{id:'other',name:'Opportunity'}],quotes,indices:['SPY','QQQ','DIA'].map((symbol,i)=>({symbol,price:560+i*12,change:[.82,1.14,-.23][i],sparkline:quotes[i].sparkline,currency:'USD'})),summary:{currencyComparable:true,positions:5,liveTotal:total,regularTotal:total-10,dayPL,dayPercent:dayPL/total*100,unrealizedPL:total*.12,unrealizedPercent:14,missingCostCount:0,extendedPL:10,extendedLabel:'After-hours move',cash:4200,realizedPL:1432.1,winners:3,losers:2},intraday:curve,benchmark:curve.map(([t,v],i)=>[t,curve[0][1]*(1+i*.000055)]),history:Array.from({length:90},(_,i)=>[now-(89-i)*86400,total*.8+i*total*.0022+Math.sin(i/6)*340]),missingSymbols:[],failedSymbols:[],stale:false,updatedAt:now,status:'Regular session',backoffSeconds:0,pollSeconds:2,trades:[{date:now-86400,symbol:'NVDA',side:'Buy',quantity:15,price:132.8,note:'Added after reviewing cash flow'},{date:now-432000,symbol:'AAPL',side:'Sell',quantity:8,price:226.4,note:'Position sizing'},{date:now-604800,symbol:'MSFT',side:'Buy',quantity:6,price:425.1,note:''}]};
let workspace={notes:{
 AAPL:{thesis:'Preview thesis: services growth may support resilient cash generation. Test the margins against the next filing.',risks:'Preview risk: product demand and regional concentration could challenge the case.',catalysts:'Review the next quarterly filing and compare cash generation with reported earnings.',stage:'researching',conviction:'medium',reviewDate:new Date(now*1000).toISOString().slice(0,10),updatedAt:now,evidence:[{id:'preview-aapl',text:'Preview observation: the latest reported periods show rising cash generation. Verify the source and period before drawing a conclusion.',source:'Illustrative preview observation',url:'',kind:'supports',createdAt:now}],questions:[{id:'preview-question',text:'What is driving the change in services margins?',done:false,createdAt:now}]},
 MSFT:{thesis:'Preview thesis: investigate how cloud investment translates into recurring cash flow.',risks:'Capital intensity and competitive pricing.',catalysts:'Track capital expenditure and the next earnings report.',stage:'monitoring',conviction:'medium',reviewDate:'',updatedAt:now-3600,evidence:[],questions:[]},
 NVDA:{thesis:'Preview thesis: assess whether demand growth is durable enough to justify the expectations in the share price.',risks:'Customer concentration, competition and cyclical demand.',catalysts:'Check reported demand, inventory and gross margins.',stage:'ready',conviction:'unrated',reviewDate:'',updatedAt:now-7200,evidence:[],questions:[{id:'preview-nvda',text:'How much growth is already assumed by the market?',done:false,createdAt:now}]}
},preferences:{selected:'AAPL'}};
const names={AAPL:'Apple Inc.',MSFT:'Microsoft Corporation',NVDA:'NVIDIA Corporation',GOOGL:'Alphabet Inc.',AMZN:'Amazon.com, Inc.',META:'Meta Platforms, Inc.'};
const metrics=[['revenue','Revenue','Income',391e9],['net_income','Net Income','Income',94e9],['operating_cash_flow','Operating Cash Flow','Cash Flow',118e9],['free_cash_flow','Free Cash Flow','Cash Flow',109e9],['cash','Cash & Equivalents','Balance Sheet',30e9],['assets','Total Assets','Balance Sheet',364e9]];
const financials=symbol=>({company:names[symbol]||symbol+' (preview company)',cik:'0000320193',updatedAt:now,annual:metrics.map(([id,label,statement,v])=>({id,label,statement,unit:'USD',points:[2022,2023,2024,2025].map((year,i)=>({label:String(year),value:v*(.72+i*.09)*(1-symbols.indexOf(symbol)*.08),filed:`${year}-11-01`,end:`${year}-09-30`,form:'10-K'}))})),quarterly:metrics.map(([id,label,statement,v])=>({id,label,statement,unit:'USD',points:[1,2,3,4].map((q,i)=>({label:`Q${q} 2025`,value:v*(.19+i*.03)*(1-symbols.indexOf(symbol)*.08),filed:`2025-0${i+2}-15`,end:`2025-0${i+1}-01`,form:'10-Q'}))})),ratios:[{label:'Gross margin',display:'46.8%',detail:'Reported gross profit / revenue'},{label:'Net margin',display:'24.1%',detail:'Reported net income / revenue'},{label:'Return on equity',display:'151.3%',detail:'Net income / equity'},{label:'Current ratio',display:'0.87×',detail:'Current assets / current liabilities'},{label:'FCF margin',display:'27.9%',detail:'Free cash flow / revenue'},{label:'Debt / equity',display:'1.52×',detail:'Reported debt / equity'}]});
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://127.0.0.1'),route=url.pathname.split('/').filter(Boolean).at(-1)||'';
  res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'");
  res.setHeader('Cache-Control','no-store');
  const files={'':'index.html','app.js':'app.js','style.css':'style.css','analytics.js':'analytics.js','desk-model.js':'desk-model.js','desk.js':'desk.js'};
  if(Object.hasOwn(files,route)){const file=files[route];res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html');const bytes=fs.readFileSync(path.join(__dirname,'../../Barista/Web',file));res.end(file==='index.html'?bytes.toString().replace('RESEARCH DESK</span>','SAMPLE DATA / RESEARCH DESK</span>').replace('MARKETBAR / INDEPENDENT THINKING','OFFLINE PREVIEW / SAMPLE DATA'):bytes);return;}
  res.setHeader('Content-Type','application/json');
  const symbol=url.searchParams.get('symbol')||'AAPL',q=quotes.find(q=>q.symbol===symbol)||quotes[0];
  if(route==='workspace'){
    if(req.method==='POST'){let raw='';for await(const chunk of req)raw+=chunk;const data=JSON.parse(raw);if(data.note)workspace.notes[data.symbol]={...data.note,updatedAt:now};if(data.preferences)Object.assign(workspace.preferences,data.preferences);res.end('{"saved":true}');return;}
    res.end(JSON.stringify(workspace));return;
  }
  const eps={yearlyForecast:{rows:[2026,2027,2028].map((year,i)=>({fiscalEnd:'Dec '+year,consensusEPSForecast:6.8+i*1.1,lowEPSForecast:5.9+i,highEPSForecast:8+i*1.2,noOfEstimates:28,up:9,down:3}))},quarterlyForecast:{rows:[1,2,3,4].map((quarter,i)=>({fiscalEnd:'Q'+quarter+' 2026',consensusEPSForecast:1.5+i*.2,lowEPSForecast:1.3+i*.2,highEPSForecast:1.8+i*.2,noOfEstimates:25,up:5,down:1}))}};
  const payload=route==='study-quote'?{symbol,kind:'stock',currency:'USD',price:211.4,change:.6,previousClose:210.14,quantity:0,researchOnly:true,receivedAt:now,observedAt:now-60,session:'Last observed bar',sparkline:quotes[0].sparkline}:route==='snapshot'?snapshot:route==='research'?financials(symbol):route==='news'?{items:[{title:'Quarterly results: a closer look at margins and cash generation',link:'https://www.sec.gov/edgar/search/',pubDate:'Illustrative preview headline',source:'Preview fixture'},{title:'Capital allocation, buybacks and the next product cycle',link:'https://finance.yahoo.com/',pubDate:'Illustrative preview headline',source:'Preview fixture'}]}:route==='expectations'?{targets:{consensusOverview:{lowPriceTarget:q.price*.85,priceTarget:q.price*1.18,highPriceTarget:q.price*1.35,buy:27,hold:9,sell:2}},eps,targetsRetrievedAt:now,epsRetrievedAt:now,errors:[]}:route==='chart'?{points:(url.searchParams.get('range')==='1D'?curve:Array.from({length:65},(_,i)=>[now-(64-i)*86400,100+i*.4+Math.sin(i/6)*3])).map(([t,v],i)=>[t,q.price*(.94+i*.0005+Math.sin(i/9+symbols.indexOf(symbol))*.012)]),currency:'USD',updatedAt:now}:{error:'Unknown fixture route'};
  res.end(JSON.stringify(payload));
});
server.listen(Number(process.env.PORT||4178),'127.0.0.1',()=>console.log('Offline research preview: http://127.0.0.1:'+server.address().port+'/'));
